# These are supported funding model platforms

github: saswatsundar123
custom:
  - https://upi.pe/saswatsundar123-1@oksbi?pn=Saswat+Sundar+Rath&tn=Thank+you+for+Supporting+me+in+developing+Open-source+software%21
  - https://paypal.me/saswatrath123321
